import { beforeEach, describe, expect, it, vi } from "vitest";
import { BrowserStudio } from "./studio";
import { DirectoryStore, cacheHash, type DiskDirectory, type DiskFile } from "./disk";
import { defaults } from "../defaults";
import type { Job, ProjectResponse } from "../types";
vi.mock("./media",()=>({media:vi.fn(async()=>({blob:new Blob(["media"],{type:"video/mp4"}),info:{duration:2,video:true,audio:true,width:64,height:64}}))}));
class Folder implements DiskDirectory {
  kind="directory" as const;children=new Map<string,Folder|DiskFile>();constructor(public name:string){}
  async queryPermission(){return "granted" as const;}async requestPermission(){return "granted" as const;}
  async getDirectoryHandle(name:string,o?:{create:boolean}):Promise<DiskDirectory>{let value=this.children.get(name);if(!value&&o?.create){value=new Folder(name);this.children.set(name,value);}if(!value||value.kind!=="directory")throw new DOMException("Missing","NotFoundError");return value;}
  async getFileHandle(name:string,o?:{create:boolean}):Promise<DiskFile>{let value=this.children.get(name);if(!value&&o?.create){let data=new Blob();value={kind:"file",name,getFile:async()=>new File([data],name),createWritable:async()=>{let pending=data;return {write:async(v:Blob|string)=>{pending=new Blob([v]);},close:async()=>{data=pending;},abort:async()=>{}};}};this.children.set(name,value);}if(!value||value.kind!=="file")throw new DOMException("Missing","NotFoundError");return value;}
  async *entries():AsyncIterableIterator<[string,DiskDirectory|DiskFile]>{yield* this.children.entries();}
  async removeEntry(name:string){if(!this.children.delete(name))throw new DOMException("Missing","NotFoundError");}
}
function locks(){const pending=new Map<string,Promise<unknown>>();return {request:async(name:string,o:{ifAvailable?:boolean},fn:(l:unknown)=>Promise<unknown>)=>{const previous=pending.get(name);if(previous&&o.ifAvailable)return fn(null);let release!:()=>void;const gate=new Promise<void>(r=>{release=r;});const chain=(previous||Promise.resolve()).then(()=>gate);pending.set(name,chain);await previous;try{return await fn({name});}finally{release();if(pending.get(name)===chain)pending.delete(name);}}};}
let root:Folder;let submit=0;let poll=0;
beforeEach(()=>{root=new Folder("selected");submit=0;poll=0;vi.stubGlobal("navigator",{locks:locks()});vi.stubGlobal("fetch",vi.fn(async(url:string,o?:RequestInit)=>{
  if(!o?.method)return Response.json({settings:{...defaults,falConfigured:true,openaiConfigured:true}});
  if(url.endsWith("/submit")){submit++;return Response.json({requestId:"existing-fal-id",statusURL:"https://queue.fal.run/fal-ai/wan/requests/existing-fal-id/status",responseURL:"https://queue.fal.run/fal-ai/wan/requests/existing-fal-id"});}
  if(url.endsWith("/poll")){poll++;return Response.json({url:null});}
  if(url.endsWith("/suggest"))return Response.json({data:[{name:"A",description:"B",motion:"C"}]});
  return Response.json({message:"validated"});
}));});
async function studio(){const s=new BrowserStudio();await s.disk.connect(root);vi.spyOn(s as unknown as {imagePayload:()=>Promise<unknown[]>},"imagePayload").mockResolvedValue([]);return s;}
async function product(s:BrowserStudio){const {project:p}=await s.api<ProjectResponse>("projects","POST");p.assets=[{id:"image",name:"image",file:"projects/"+p.id+"/assets/image.png",hash:"image-hash",size:4,mime:"image/png",kind:"image",origin:"upload"}];p.primaryId="image";p.scenes=[{id:"scene",sourceId:"image",name:"scene",prompt:"studio",motion:"slow",original:true}];await s.disk.write(p.assets[0].file,new Blob(["file"]));await s.disk.writeJSON("projects/"+p.id+"/project.json",p);return p;}
async function expire(s:BrowserStudio,id:string){const j=(await s.disk.json<Job>("jobs/"+id+".json"))!;j.updatedAt=new Date(Date.now()-10000).toISOString();await s.disk.writeJSON("jobs/"+id+".json",j);}
describe("browser directory persistence",()=>{
  it("stores projects/settings in chosen folder and reopens independently",async()=>{const s=await studio(),p=await product(s);await s.api("settings","PUT",{falKey:"local-secret"});const reopened=await studio();expect((await reopened.api<ProjectResponse>("projects/"+p.id)).project.primaryId).toBe("image");const c=await reopened.api<{settings:{falConfigured:boolean;falKey?:string}}>("settings");expect(c.settings.falConfigured).toBe(true);expect(c.settings.falKey).toBeUndefined();expect((await reopened.disk.read("settings.json")).size).toBeGreaterThan(0);});
  it("normalizes prompts and hashes media/settings without keys",async()=>{expect(await cacheHash({b:1,a:"  café\n test "})).toBe(await cacheHash({a:"cafe\u0301 test",b:1}));const s=await studio(),p=await product(s);expect(await s.key(defaults,p,"video",p.scenes[0])).toBe(await s.key({...defaults,falKey:"changed",openaiKey:"secret"},p,"video",p.scenes[0]));});
  it("deduplicates double clicks, reloads with same fal ID and retries polling without submitting",async()=>{
    const s=await studio(),p=await product(s);const results=await Promise.all([s.api<{job:Job}>("projects/"+p.id+"/jobs","POST",{action:"video",sceneId:"scene"}),s.api<{job:Job}>("projects/"+p.id+"/jobs","POST",{action:"video",sceneId:"scene"})]);expect(results[0].job.id).toBe(results[1].job.id);
    await s.api("jobs/tick","POST",{projectId:p.id});expect(submit).toBe(1);
    const r=await studio();await expire(r,results[0].job.id);await r.api("jobs/tick","POST",{projectId:p.id});expect(poll).toBe(1);expect(submit).toBe(1);
    const j=(await r.disk.json<Job>("jobs/"+results[0].job.id+".json"))!;j.status="failed";await r.disk.writeJSON("jobs/"+j.id+".json",j);await r.api("jobs/"+j.id+"/retry","POST",{});await expire(r,j.id);await r.api("jobs/tick","POST",{projectId:p.id});expect(submit).toBe(1);expect(poll).toBe(2);
  });
  it("does not resubmit an ambiguous paid call after closing tab",async()=>{const s=await studio(),p=await product(s);const {job:j}=await s.api<{job:Job}>("projects/"+p.id+"/jobs","POST",{action:"video",sceneId:"scene"});j.phase="submitting";j.status="running";await s.disk.writeJSON("jobs/"+j.id+".json",j);await s.api("jobs/tick","POST",{projectId:p.id});expect(submit).toBe(0);expect((await s.disk.json<Job>("jobs/"+j.id+".json"))?.status).toBe("uncertain");});
  it("shares fal job across projects with identical input",async()=>{const s=await studio(),a=await product(s),b=await product(s);await s.api("projects/"+a.id+"/jobs","POST",{action:"video",sceneId:"scene"});await s.api("jobs/tick","POST",{projectId:a.id});await s.api("projects/"+b.id+"/jobs","POST",{action:"video",sceneId:"scene"});await s.api("jobs/tick","POST",{projectId:b.id});expect(submit).toBe(1);expect((await s.api<ProjectResponse>("projects/"+b.id)).jobs[0].requestId).toBe("existing-fal-id");});
  it("uses successful cache, checks file existence, deletes cache without original assets",async()=>{const s=await studio(),p=await product(s);const jobPath="projects/"+p.id+"/jobs";await s.api(jobPath,"POST",{action:"suggest"});await s.api("jobs/tick","POST",{projectId:p.id});await s.api(jobPath,"POST",{action:"suggest"});await s.api("jobs/tick","POST",{projectId:p.id});expect((await s.api<ProjectResponse>("projects/"+p.id)).jobs.some(j=>j.cached)).toBe(true);await s.api("cache","DELETE");expect((await s.disk.read(p.assets[0].file)).size).toBe(4);expect(await s.api("cache")).toEqual({bytes:0,entries:0});});
  it("does not reuse a cache result whose file has been deleted",async()=>{const s=await studio();const key=await cacheHash({input:"test"});await s.disk.writeJSON("cache/"+key+".json",{key,file:"cache/deleted.bin",mime:"video/mp4"});const cache=s as unknown as {cached:(k:string)=>Promise<unknown>};expect(await cache.cached(key)).toBeNull();await s.disk.write("cache/deleted.bin",new Blob(["video"]));expect(await cache.cached(key)).not.toBeNull();});
  it("audio changes alter composition key without altering Wan key",async()=>{const s=await studio(),p=await product(s);p.assets.push({id:"video",name:"video",file:"video.mp4",hash:"video-hash",size:4,mime:"video/mp4",kind:"video"},{id:"audio",name:"audio",file:"audio.m4a",hash:"audio-hash",size:4,mime:"audio/mp4",kind:"audio"});p.scenes[0].videoId="video";const key=await s.key(defaults,p,"video",p.scenes[0]),final=await s.key(defaults,p,"compose");p.audio.enabled=true;p.audio.audioId="audio";p.audio.volume=0.5;expect(await s.key(defaults,p,"video",p.scenes[0])).toBe(key);expect(await s.key(defaults,p,"compose")).not.toBe(final);});
  it("rejects missing permission and path traversal",async()=>{const d=new DirectoryStore();await expect(d.write("projects/a.json","{} ")).rejects.toThrow("thư mục");await d.connect(root);await expect(d.write("../settings.json","{} ")).rejects.toThrow("Đường dẫn");});
});
